#   create/manage many Kind=AWSNodeGroup resources
#   roll them one by one
apiVersion: eks.nlm.tech/v1alpha1
kind: Cluster
metadata:
  name: mj-eso
spec: 
  region: eu-central-1
  providerConfigRef:
    name: default
  nodeGroupSpec:
    # define a strategy for the node rollout process
    # this allows you to parallelize it.
    updateStrategy: 
      rollingUpdate:
        maxUnavailable: 1

    groups:
    - name: general
      ami: ami-0b9b30c466935db49 # ami-01728bd5cea21d157
      minSize: 1
      maxSize: 1
      desiredSize: 1
    # - name: bar
    #   ami: ami-0b9b30c466935db49
    #   minSize: 1
    #   maxSize: 1
    #   desiredSize: 1
